apiVersion: apps/v1
kind: Deployment
metadata:
    name: openliberty-12factor-app-a-deployment
spec:
    selector:
        matchLabels:
            app: 12factor-app-a
    replicas: 2
    template:
        metadata:
            labels:
                app: 12factor-app-a
        spec:
            containers:
                - name: 12factor-app-a
                  image: openliberty-12factor-app-a:1.0-SNAPSHOT
                  ports:
                      - containerPort: 9080
                      - containerPort: 9443
                  env:
                      - name: svcBHost
                        value: openliberty-12factor-app-b-deployment
                      - name: svcBPort
                        value: "9081"

